# Generated by Django 5.0.7 on 2024-11-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
